Add option to GetStatementOfAccount::create()
nemiah/phpFinTS pull request #378
Opened 2022-07-18 19:23 UTC by nemiah

…to include unbooked transactions again

2022-07-18 19:35 UTC, nemiah commented
@Philipp91 weißt du, was sein Problem is?

2022-07-18 19:37 UTC, Philipp91 requested changes

2022-07-18 19:37 UTC, Philipp91 commented on lib/Fhp/Action/GetStatementOfAccount.php
> +			if($this->includeUnbooked)
`&& $hikaz->getNichtGebuchteUmsaetze() != null`

2022-07-18 19:37 UTC, Philipp91 commented on Samples/statementOfAccount.php
> +    	echo "Booked      : " . ($transaction->getBooked() ? "true" : "false").PHP_EOL;
Leerzeichen um `.`

2022-07-18 19:37 UTC, Philipp91 commented on lib/Fhp/Action/GetStatementOfAccount.php
> +			$this->rawMT940 .= $hikaz->getGebuchteUmsaetze()->getData();
Mit Leerzeichen statt Tabs einrücken.

2022-07-18 19:37 UTC, Philipp91 commented on lib/Fhp/Segment/KAZ/HIKAZv4.php
> +    public function getNichtGebuchteUmsaetze(): Bin
Das müsste dann auch ins `HIKAZ`-Interface.

2022-07-18 19:37 UTC, Philipp91 commented on lib/Fhp/Segment/KAZ/HIKAZv4.php
> +    public function getNichtGebuchteUmsaetze(): Bin
Der Rückgabewert sollte `Bin|null` sein.

2022-07-21 20:05 UTC, Philipp91 commented
https://memegenerator.net/instance/86375445

2022-07-21 20:20 UTC, nemiah commented
Also das ist ja mal ein Spießrutenlauf :angry: 
Weißt du, was noch sein Problem ist?

2022-07-21 20:43 UTC, Philipp91 commented
Ich versuche mal mein Glück: https://github.com/nemiah/phpFinTS/pull/381

2022-07-22 08:21 UTC, nemiah commented
Hmm, was will er mir damit sagen?
1) phpFinTS/lib/Fhp/Action/GetStatementOfAccount.php (braces)

2022-07-22 08:33 UTC, Philipp91 commented
Weiß ich nicht, aber `composer cs-fix` sollte es beheben.

2022-07-22 09:46 UTC, Philipp91 commented
Ich glaube, bei mir geht's mit PHP 8.1. Vielleicht `composer update` um die neueste Version (3.9.5) zu installieren? (Siehe auch `php-cs-fixer -vvv`)

2022-07-22 11:59 UTC, nemiah commented
Wow, verrückter :hankey: !

2022-07-22 11:59 UTC, merged